### ISSUE TITLE
Android 7.1 issue

### ISSUE THREAD

**Issue by gaara92** [chrisboyle/keytest#1]
Hi,
I don't know if your app is still in development. I write here by hasard.
I would like to use it for Android 7.1 (RT Android for Raspberry Pi) to remap mouse buttons.
The apk is installed, but no response in the app's terminal. No problem with Android 4.4.

It is possible to fix it?

**Comment by chrisboyle** [comment]
To be honest I'm surprised if it ever said anything for mouse buttons. It's only supposed to catch keys; if you look at the source it just uses [`Activity.onKeyDown`](https://developer.android.com/reference/android/app/Activity.html#onKeyDown%28int,%20android.view.KeyEvent%29) which is documented as being called for key events. If that's not working on your device I don't immediately have any ideas... what other buttons have you tried? Volume up/down would probably say something.

**Comment by gaara92** [comment]
Hi, thanks for your answer. I'm using a Raspberry Pi 3 (nano pc), so I havn't volume button. I have tried to get a key with the keyboard, but no output with any button.
Here is a screenshot with RPi3:
![2017_02_27_13 58 01](https://cloud.githubusercontent.com/assets/5517870/23362303/772d880c-fcf5-11e6-968c-3f7133ac0c78.png)
I'm using this Android version: http://rtandroid.embedded.rwth-aachen.de/downloads/raspberry-pi/
Maybe can I read a log somewhere?

**Comment by chrisboyle** [comment]
I've no more ideas I'm afraid. The app doesn't log anything because the main screen **is** the log - there is no more information that I receive from Android. This tiny utility is really very simple, its entire behaviour is defined in [these few lines](https://github.com/chrisboyle/keytest/blob/master/src/name/boyle/chris/keytest/KeyTest.java) - it just says "whenever Android tells me a key is pressed down, write the keycode and the event to the screen". If nothing is on the screen it means Android did not tell me that anything happened at all, so there's nothing I can do. It really isn't receiving any more information than what it is displaying (in this case, nothing).

Sorry I wasn't able to help more.
